# -*- coding: utf-8 -*-
"""Fetch a 20px-wide JPEG of every image and inline it as a base64 placeholder,
   so a lazily-loaded photograph never shows as an empty grey box."""
import urllib.request, base64, os, sys
sys.path.insert(0, os.path.dirname(__file__))
from content import MEDIA
from gen_media import ORIGIN, UA

out = ['# -*- coding: utf-8 -*-',
       '"""Generated by gen_lqip.py — 20px placeholders, base64. Do not edit."""',
       'LQIP = {']
for key, m in MEDIA.items():
    if m.get("mark"):
        continue
    oid = ORIGIN[m["src"]]
    w = 20
    h = max(1, int(round(w * m["h"] / m["w"])))
    u = ("https://static.wixstatic.com/media/%s/v1/fill/w_%d,h_%d,al_c,q_30,blur_2/%s"
         % (oid, w, h, oid))
    req = urllib.request.Request(u, headers={"User-Agent": UA, "Accept": "image/jpeg,image/*"})
    d = urllib.request.urlopen(req, timeout=45).read()
    b = base64.b64encode(d).decode()
    out.append('    %r: "data:image/jpeg;base64,%s",' % (key, b))
    print("%-12s %5d bytes -> %d b64" % (key, len(d), len(b)))
out.append('}')
open(os.path.join(os.path.dirname(__file__), "lqip.py"), "w").write("\n".join(out) + "\n")
